"""
This type stub file was generated by pyright.
"""

from enum import Enum
from pydantic import BaseModel

"""
Typing for Group Privileges
"""
class Privilege(Enum):
    """Supported privileges for a repos"""
    READ = ...
    WRITE = ...
    ADMIN = ...
    def __str__(self) -> str:
        ...
    


class GroupPrivilege(BaseModel):
    """
    Privilege/group view
    """
    privilege = ...
    group = ...
    def __eq__(self, other) -> bool:
        ...
    


class GroupPrivileges(BaseModel):
    """Group all privilegies"""
    privileges = ...


