"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel

"""
Typing for Pipelines Config

ht"""
class RepositoryPipelinesConfiguration(BaseModel):
    enabled = ...
    def __eq__(self, other) -> bool:
        ...
    


class StateResult(BaseModel):
    name: str
    ...


class State(BaseModel):
    name: str
    result: StateResult
    ...


class Commit(BaseModel):
    hash: str
    ...


class Target(BaseModel):
    ref_type: str
    ref_name: str
    commit: Commit
    ...


class PipelineUUID(BaseModel):
    state: State
    target: Target
    build_number: str
    ...


