"""
This type stub file was generated by pyright.
"""

from enum import Enum
from pydantic import BaseModel

"""
Typing for Permissions

https:/"""
class PermissionEnum(str, Enum):
    READ = ...
    WRITE = ...
    ADMIN = ...


class Permission(BaseModel):
    """
    https://developer.atlassian"""
    READ_CAPABILITIES = ...
    WRITE_CAPABILITIES = ...
    permission = ...
    repository = ...
    def has_write(self): # -> bool:
        ...
    


