"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination, ApiLeaf
from ...typing.repositories import branch_restrictions

class BranchRestriction(ApiLeaf, branch_restrictions.BranchRestriction):
    """
    Manages one branch restrict"""
    def __init__(self, api_url, network, id=..., data=..., parent=...) -> None:
        ...
    


class BranchRestrictions(ApiBranchPagination):
    """
    Manages branch restrictions"""
    def __init__(self, api_url_reposlug, network) -> None:
        ...
    
    def by_id(self, id): # -> BranchRestriction:
        ...
    


