"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination, ApiLeaf
from ...typing.repositories import deploykey

class DeployKey(ApiLeaf, deploykey.DeployKey):
    """
    Manages SSH Keys

    https"""
    def __init__(self, api_url, network, key_id=..., data=..., parent=...) -> None:
        ...
    


class DeployKeys(ApiBranchPagination):
    """
    https://developer.atlassian"""
    def __init__(self, api_url_reposlug, network) -> None:
        ...
    
    def by_key_id(self, key_id): # -> DeployKey:
        ...
    


