"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination, ApiLeaf
from ...typing.repositories import pipeline

class PipelineUUID(ApiLeaf, pipeline.PipelineUUID):
    def __init__(self, api_url, network, id=..., data=..., parent=...) -> None:
        ...
    


class Pipelines(ApiBranchPagination):
    """
    Manages Pipelines

    http"""
    def __init__(self, api_url_reposlug, network) -> None:
        ...
    


