"""
This type stub file was generated by pyright.
"""

from ...api import ApiLeaf
from ...typing.repositories import pipeline

class PipelinesConfig(ApiLeaf, pipeline.RepositoryPipelinesConfiguration):
    """
    Manage Pipelines Configuati"""
    def __init__(self, api_url_reposlug, network, data=..., parent=...) -> None:
        ...
    
    async def enable(self): # -> None:
        """Enable pipelines
        
      """
        ...
    
    async def disable(self): # -> None:
        """Disable pipelines
        
     """
        ...
    


