"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination, ApiLeaf
from ...typing.repositories import pullrequests

class PullRequest(ApiLeaf, pullrequests.PullRequest):
    """
    Manages Pull Request

    h"""
    def __init__(self, api_url, network, id=..., data=..., parent=...) -> None:
        ...
    


class PullRequests(ApiBranchPagination):
    """
    https://developer.atlassian"""
    def __init__(self, api_url_refs, network) -> None:
        ...
    
    def get(self, filter=...): # -> NetworkPagination:
        """Override the ApiBranchPagination"""
        ...
    
    def by_id(self, id): # -> PullRequest:
        ...
    


