"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination, ApiLeaf
from ...typing import refs

class Branch(ApiLeaf, refs.Branch):
    """
    Manages Branch

    https:/"""
    def __init__(self, api_url, network, name=..., data=..., parent=...) -> None:
        ...
    


class Branches(ApiBranchPagination):
    """
    https://developer.atlassian"""
    def __init__(self, api_url_refs, network) -> None:
        ...
    
    def by_name(self, name): # -> Branch:
        ...
    


class Refs:
    def __init__(self, api_url_reposlug, network) -> None:
        ...
    


