"""
This type stub file was generated by pyright.
"""

from ...api import ApiLeaf
from ...typing.repositories import repository

class RepoSlug(ApiLeaf, repository.Repository):
    """
    Manages repository

    htt"""
    def __init__(self, network, workspace_name, repo_slug_name, data=..., parent=...) -> None:
        ...
    
    def pipelines_config(self): # -> PipelinesConfig:
        """Pipelines config API accessor"""
        ...
    
    def deploy_keys(self): # -> DeployKeys:
        """Deploy Keys API accessor"""
        ...
    
    def branch_restrictions(self): # -> BranchRestrictions:
        """Branch restrictions API accessor"""
        ...
    
    def group_privileges(self): # -> GroupPrivilegesRepoSlug:
        """Group Privileges API accessor"""
        ...
    
    def pipelines(self): # -> Pipelines:
        """Find Pipelines accessor"""
        ...
    
    def refs(self): # -> Refs:
        """Branches and tags accessor"""
        ...
    
    def src(self): # -> Src:
        """Source files accessor"""
        ...
    
    def pullrequests(self): # -> PullRequests:
        """Pull Requests accessor"""
        ...
    


