"""
This type stub file was generated by pyright.
"""

"""
https://developer.atlassian.com"""
class Repositories:
    """
    https://developer.atlassian"""
    def __init__(self, network) -> None:
        ...
    
    def repo_slug(self, workspace_name, repo_slug_name): # -> RepoSlug:
        """Repository API shortcut accessor"""
        ...
    


