"""
This type stub file was generated by pyright.
"""

class Src:
    """
    Manages source code files

"""
    def __init__(self, api_url_reposlug, network) -> None:
        ...
    
    async def download(self, node, path):
        ...
    
    async def upload_pure_text(self, filename, txt, message, author, branch):
        ...
    


