"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination, ApiLeaf
from ...typing.webhooks import webhook

class WebHookUUID(ApiLeaf, webhook.WebHookUUID):
    """
        Manages one webhook

  """
    def __init__(self, api_url_workspace, network, uid=..., data=..., parent=...) -> None:
        ...
    


class WebHooks(ApiBranchPagination):
    """
    Manages WebHooks

    https"""
    def __init__(self, network) -> None:
        ...
    
    async def get_by_workspace(self, api_url_workspace, network): # -> None:
        ...
    
    async def get_by_workspace(self, api_url_workspace): # -> None:
        ...
    
    async def get_by_repository_name(self, repo_full_name):
        """Get hooks for a specific reposit"""
        ...
    


