"""
This type stub file was generated by pyright.
"""

class ApiLeaf:
    """
    A typical Leaf endpoint on """
    GET = ...
    UPDATE = ...
    DELETE = ...
    CREATE = ...
    def __init__(self, api_url, network, api_unsupported=...) -> None:
        ...
    
    async def get(self): # -> None:
        """
        GET
        """
        ...
    
    async def update(self): # -> None:
        """
        PUT
        """
        ...
    
    async def delete(self): # -> None:
        """
        DELETE
        """
        ...
    
    async def create(self): # -> None:
        """
        POST

        Most of t"""
        ...
    


class ApiBranchPagination:
    """
    A typical Branch in an endp"""
    NEW = ...
    def __init__(self, api_url, network, cast_leaf, api_unsupported=...) -> None:
        ...
    
    def get(self, filter=..., pagelen=...): # -> NetworkPagination:
        """
        GET with filter support"""
        ...
    
    def new(self):
        """
        Create a leaf that will"""
        ...
    


