"""
This type stub file was generated by pyright.
"""

class AioBitbucketException(Exception):
    ...


class ApiUnsupported(AioBitbucketException):
    def __init__(self, call_type) -> None:
        ...
    


class NetworkGeneric(AioBitbucketException):
    def __init__(self, msg, status, details) -> None:
        ...
    
    def getNetworkResponse(self): # -> tuple[Unknown, Unknown]:
        ...
    


class NetworkBadRequest(NetworkGeneric):
    def __init__(self, status, details) -> None:
        ...
    


class NetworkUnauthorized(NetworkGeneric):
    def __init__(self, status, details) -> None:
        ...
    


class NetworkForbidden(NetworkGeneric):
    def __init__(self, status, details) -> None:
        ...
    


class NetworkNotFound(NetworkGeneric):
    def __init__(self, status, details) -> None:
        ...
    


class NetworkServerErrors(NetworkGeneric):
    def __init__(self, status, details) -> None:
        ...
    


class SessionAlreadyExist(AioBitbucketException):
    def __init__(self) -> None:
        ...
    


