"""
This type stub file was generated by pyright.
"""

import aiohttp

"""
Network Management to request B"""
logger = ...
class Network:
    """
    Network

    Support standa"""
    def __init__(self, base_url) -> None:
        ...
    
    def basic_auth(self, username, password): # -> BasicAuth:
        ...
    
    def create_session(self, headers=..., auth=...): # -> None:
        ...
    
    async def close_session(self): # -> None:
        ...
    
    async def answer(self, resp: aiohttp.ClientResponse): # -> Any | str:
        ...
    
    async def get(self, url: str): # -> Any | str:
        ...
    
    async def put(self, url, payload): # -> Any | str:
        ...
    
    async def post(self, url, payload): # -> Any | str:
        ...
    
    async def post_form(self, url, payload): # -> Any | str:
        ...
    
    async def delete(self, url): # -> None:
        ...
    


class NetworkPagination:
    """
    Generic support for paginat"""
    def __init__(self, url: str, network, dynamic_cast=..., pagelen=...) -> None:
        ...
    
    def __aiter__(self): # -> Self@NetworkPagination:
        ...
    
    async def __anext__(self):
        ...
    
    async def fetch(self): # -> None:
        ...
    


