"""
This type stub file was generated by pyright.
"""

from pydantic import BaseModel

class Target(BaseModel):
    hash = ...
    date = ...
    message = ...


class Branch(BaseModel):
    name = ...
    target = ...


