"""
This type stub file was generated by pyright.
"""

from ...api import ApiBranchPagination

class Repositories(ApiBranchPagination):
    """
    https://developer.atlassian"""
    def __init__(self, network) -> None:
        ...
    
    async def get_by_full_name(self, repo_full_name):
        """Get permissions for a specific r"""
        ...
    


class Permissions:
    """
    https://developer.atlassian"""
    def __init__(self, network) -> None:
        ...
    


class User:
    """
    Covering https://developer."""
    def __init__(self, network) -> None:
        ...
    


