"""
This type stub file was generated by pyright.
"""

from ...typing.legacy.group_privileges import Privilege

class GroupPrivilegesRepoSlug:
    """
    Use the group-privileges re"""
    def __init__(self, network, workspace_name, repo_slug_name) -> None:
        ...
    
    async def get(self): # -> GroupPrivileges:
        """GET a list of privileged groups """
        ...
    
    async def add(self, group, privilege: Privilege, group_owner=...): # -> None:
        """PUT group privileges on a reposi"""
        ...
    
    async def delete(self, group, group_owner=...): # -> None:
        """DELETE group privileges from a r"""
        ...
    


